FROM python:3.10

WORKDIR /app

RUN apt-get update && apt-get install -y chromium chromium-driver

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY scrape/ ./scrape
COPY staging/ ./staging

CMD ["python", "scrape/scraping.py"]