FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir uv && \
    uv pip install --system -r requirements.txt

COPY . .

ENV PYTHONUNBUFFERED=1

CMD ["python", "warehouse/main.py"]