services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12341234
      POSTGRES_DB: avito_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  scraper:
    build:
      context: ..
      dockerfile: docker/Dockerfile.scraper
    container_name: avito_scraper
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ../scrape:/app/scrape
      - ../staging:/app/staging
      - ../logs:/app/logs
    env_file:
      - ../.env
    command: python scrape/scraping.py

  cleaner:
    build:
      context: ..
      dockerfile: docker/Dockerfile.cleaner
    container_name: avito_cleaner
    restart: on-failure
    depends_on:
      scraper:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
    volumes:
      - ../clean:/app/clean
      - ../staging:/app/staging
      - ../logs:/app/logs
    env_file:
      - ../.env
    command: python clean/cleaning.py

  warehouse:
    build:
      context: ..
      dockerfile: docker/Dockerfile.warehouse
    container_name: avito_warehouse
    restart: on-failure
    depends_on:
      cleaner:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
    volumes:
      - ../warehouse:/app/warehouse
      - ../clean:/app/clean
      - ../logs:/app/logs
    env_file:
      - ../.env
    command: python warehouse/main.py

volumes:
  postgres_data: