FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y chromium chromium-driver

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

CMD ["python", "scrape/scraping.py"]